### ISSUE TITLE
Doesn't work update of minicart's count 

### ISSUE THREAD

**Issue by Mr-Bam** [code4business/freeproduct2#12]
I have condition when subtotal price will be more than 1500.
Problem is in when we add two products with price 849 (subtotal 1698), minicart count equal 2, but in general is 3, because we have add free product by condition. Also, if we add one product more, than it updates well. After that if we want to do subtotal price less then 1500, our free product will remove from cart, but count of minicart will not update. 
So, I think that we have to do update of minicart count every time when we add free product or remove.
I have thought it can be in FreeProduct\Observer\RemoveGiftItems.php. But, unfortunately, I can't understand how to do it only by php without js.
Here is screenshots:
Here is correct
![image](https://user-images.githubusercontent.com/21306696/52328970-1c9b1880-29fa-11e9-9897-c415d6085969.png)
Here is wrong showing
![image](https://user-images.githubusercontent.com/21306696/52329023-46ecd600-29fa-11e9-8754-401f6ab34d20.png)
Here is again correct
![image](https://user-images.githubusercontent.com/21306696/52329061-61bf4a80-29fa-11e9-8cdd-7e687dd59bf8.png)
If we change qty of product to 1, we have the same situation like in the first screen.

**Comment by domeglic** [comment]
There is a new version in develop branch that we are currently testing that should fix this problem.

**Comment by Mr-Bam** [comment]
Okay. Thanks a lot. Good luck!

ср, 6 февр. 2019 г. в 14:27, Dominik Meglič <notifications@github.com>:

**Comment by domeglic** [comment]
Should be fixed by #13
