### ISSUE TITLE
Bugs with login

### ISSUE THREAD

**Issue by Mr-Bam** [code4business/freeproduct2#14]
After completing condition for adding free product, you should go to checkout and try login there. After that you can see different bugs for example: 
- cart subtotal will be null in mini cart;
- adding new product to cart and mini cart too.
If you haven't bugs, please, try these actions again to see it. It doesn't work every time.

**Comment by domeglic** [comment]
I have tried it several times on Magento v2.2.7 but I cannot reproduce the bug.
Which version of Magento and module are you using?

**Comment by Mr-Bam** [comment]
I have the same version and the last your module version.
