### ISSUE TITLE
Product type

### ISSUE THREAD

**Issue by nadroj467** [code4business/freeproduct2#17]
Hi,

This great extension but does not integrate well with API order export and our 3rd party accounting software as we get error

Export did not succeed Unsupported product type freeproduct_gift  

Is it possible to remain product type 'Simple Product' on free gift?

**Comment by domeglic** [comment]
Product type is used to easily add a quote item renderer (that has no delete option). The type is set in a custom option but it looks like when converted to order item it takes the custom option value instead of the real one.

I will have a look into it.

**Comment by nadroj467** [comment]
Many Thanks, would be great to get a solution on it

**Comment by domeglic** [comment]
Product type is now correct type when order item is created. [Version 1.2.6](https://github.com/code4business/freeproduct2/tree/1.2.6)

Commit: 427cd5ba4596002517811d28c58abde528ef124d

**Comment by nadroj467** [comment]
Great, thanks!
