### ISSUE TITLE
ISSUE on cart page when you add any product custom option as required.

### ISSUE THREAD

**Issue by codhepstack** [code4business/freeproduct2#18]
## Error on cart page ###

When you add a free product rule and configure the free product with the custom options as required, it throws an error **Call to a member function getQty() on string in MAGENTO_DIR/app/code/C4B/FreeProduct/SalesRule/Action/GiftAction.php:100**

**Comment by domeglic** [comment]
Products with any kind of configuration are not supported as there would be no way to configure them when they are added.
