### ISSUE TITLE
A second gift product is added when payment fails

### ISSUE THREAD

**Issue by kolaente** [code4business/freeproduct2#20]
### Preconditions

- Magento version: 2.3.2-p2
- Module version: 1.2

### Settings / Sale Rules

This: 
![grafik](https://user-images.githubusercontent.com/13721712/69716918-5cf39080-110b-11ea-9b86-833ce6e4e020.png)
In combination with a coupon code.

### Steps to reproduce
1. Put a product applicable for a gift product in cart
2. Enter the coupon
3. Gift product is added to cart
4. Make the checkout, but with failing payment information, so the checkout itself fails and redirects to the checkout page. This probably depends on the payment provider, we achived this by entering a test credit card without a card holder.

### Expected result
1. Error message from the payment processor, one gift product in cart

### Actual result
1. Error message from the payment Processor, two gift products in cart, one with a price of 0€ and one with the actual price:

![grafik](https://user-images.githubusercontent.com/13721712/69717482-6e896800-110c-11ea-8a28-d572a57c2d25.png)

You can also see the price of the second added gift product is not taken into account for the total price.

**Comment by domeglic** [comment]
Thank you for the report, we will look into it

**Comment by domeglic** [comment]
@kolaente  I tried to reproduce it but don't know how to get the case where I am redirected to cart. All the payments I am able to test with fail in the checkout and do not redirect to cart. Could you tell me which payment gateway it is?

**Comment by amenk** [comment]
I am a colleague of @kolaente. We use CommerzbankWebPOS from Customweb / sellxed for Magento 2. It works as follows:

1. Press "submit order"
2. Redirect to Payment gateway (order is created)
3. No for example you might cancel the payment on the payment page
4. Order is canceled, new cart is created, redirect to cart

In the end of the day it's a strange behavior of the payment plugin, but it seems to be not totally uncommon that the payment gateway behaves like this.
