### ISSUE TITLE
Keep Original Price in Order

### ISSUE THREAD

**Issue by amenk** [code4business/freeproduct2#21]
### Preconditions
- Magento version:  2.3.2-p2
- Module version: 1.2.6

### Settings / Sale Rules
1. Product B which costs 289€ is added as free product, if product A is in cart

### Steps to reproduce
1. Order product A
2. Add coupon code
3. Product B is added with zero price
4. finish the order
5. Fetch the Order via REST

### Expected result

The order item should have

     <original_price>289.0000</original_price>

### Actual result

The order item has

      <original_price>0</original_price>

**Comment by amenk** [comment]
Shall we make PR for this? Should the feature be configurable? I think it would cause also the free product original price to be displayed as discount?

**Comment by domeglic** [comment]
I will accept a PR. I am not familiar with how original price works, but as long as it doesn't affect the discount it should be fine without a configuration.

**Comment by amenk** [comment]
@domeglic Can you give me a hint where the zero-price is set in the module?

**Comment by domeglic** [comment]
It is not actually set, the price should be set in row_total. Those are set by subtotal collector which was run before discount, where gifts are added.
I realize now that it is probably a bad idea we did not set it explicitly to 0.

The place to set it would probably be `\C4B\FreeProduct\SalesRule\Action\AbstractGiftAction::calculate` after you get the $quoteItem back.

**Comment by amenk** [comment]
Wondering if we had to change the getDiscountData - because in our logic, there would be a discount of 100% of the free product's price
What do you think?

**Comment by domeglic** [comment]
discountData is what is applied to whatever item triggered the sales rule (or the first one if the sales rule is for the cart). So in our case the discount is 0% because the existing cart items don't get any price modifications.

```
/**
     * @param \Magento\SalesRule\Model\Rule\Action\Discount\Data $discountData
     * @param \Magento\Quote\Model\Quote\Item\AbstractItem $item
     * @return $this
     */
    protected function setDiscountData($discountData, $item)
    {
        $item->setDiscountAmount($discountData->getAmount());
        $item->setBaseDiscountAmount($discountData->getBaseAmount());
        $item->setOriginalDiscountAmount($discountData->getOriginalAmount());
        $item->setBaseOriginalDiscountAmount($discountData->getBaseOriginalAmount());

        return $this;
    }
```

**Comment by amenk** [comment]
Ah okay --- understood.

But I think the logic we are thinking about is, to have 100% discount for automatically added, *free product*. Would that be in scope of the module? Maybe via config option? It's quite an case though ...
Reasons is the way our customer's ERP is processing things.

**Comment by amenk** [comment]
This basically works in https://github.com/code4business/freeproduct2/blob/master/SalesRule/Action/AbstractGiftAction.php#L94

                $giftProduct = $this->getGiftProduct($sku);
                $quoteItem = $item->getQuote()->addProduct($giftProduct, $giftQty);
                $quoteItem->setPrice($giftProduct->getPrice());
                $quoteItem->setDiscountAmount($giftProduct->getPrice());

and leads to a order like this:

	  {
	      "amount_refunded": 0,
	      "base_amount_refunded": 0,
	      "base_discount_invoiced": 0,
	      "base_price": 0,
	      "base_row_invoiced": 0,
	      "base_row_total": 0,
	      "base_tax_invoiced": 0,
	      "created_at": "2020-03-05 17:03:30",
	      "discount_amount": 205.9,
	      "discount_invoiced": 0,
	      "free_shipping": 0,
	      "is_qty_decimal": 0,
	      "is_virtual": 0,
	      "item_id": 3,
	      "name": "free product sample",
	      "no_discount": 0,
	      "order_id": 1,
	      "original_price": 0,
	      "price": 205.9,
	      "product_id": 3299,
	      "product_type": "simple",
	      "qty_canceled": 0,
	      "qty_invoiced": 0,
	      "qty_ordered": 1,
	      "qty_refunded": 0,
	      "qty_shipped": 0,
	      "quote_item_id": 9143,
	      "row_invoiced": 0,
	      "row_total": -205.9,
	      "sku": "1031723",
	      "store_id": 4,
	      "tax_invoiced": 0,
	      "updated_at": "2020-03-05 17:03:30",
	      "row_total_incl_tax": -205.9,
	      "base_row_total_incl_tax": 0
	    }
such a negative row total does not seem right.

Also on the cart it looks this: Price = 205.9 - row total = 0
So this behavior maybe really show be added as an option "show original price for free items" which can make sense in marketing :)

I think without the setDiscountAmount() it might be better, because now we have a negative row total

**Comment by amenk** [comment]
Another option might be to influence the original_price in the order. This can be accomplished by overwriting

\Magento\Quote\Model\Quote\Item\AbstractItem::getOriginalPrice

    public function aroundGetOriginalPrice(\Magento\Quote\Model\Quote\Item $subject, callable $proceed)

and return the product's original price

**Comment by amenk** [comment]
I will make a PR, using aroundGetOriginalPrice method

**Comment by domeglic** [comment]
I guess this was never an issue before because adding a product during collectTotals is bypassing all the other calculation anyway.

**Comment by amenk** [comment]
Actually this is only an issue for us because of the ERP where orders get pushed too -- so it's quite an edge case :) But it's nicer when the original_price is set

**Comment by domeglic** [comment]
What if you set original price when the gift is added and then also set custom price to 0? This should keep the price 0 but let you get original price

**Comment by amenk** [comment]
@domeglic There is no original price in the quote, it is fetched dynamically, that is why we need that plugin. Merge request: https://github.com/code4business/freeproduct2/pull/24

**Comment by amenk** [comment]
@domeglic is there a chance to get the PR merged quickly? That would save me to work with composer patches / using the forked repo in my installation. Feel free to comment on the PR - or if you do not have time at the moment, also no problem :)
