### ISSUE TITLE
How can I specify quantity of free product to add to cart ?

### ISSUE THREAD

**Issue by sayanthkoroth** [code4business/freeproduct2#25]
It will be great If it possible to set the quantity of free product to add to cart !

**Comment by domeglic** [comment]
This is already possible: https://github.com/code4business/freeproduct2#configuration

**Comment by sayanthkoroth** [comment]
So If I specify multiple products with comma seperated, then is it possible to specify quantity for individual products in the same manner ?

**Comment by domeglic** [comment]
Sorry, your initial question was not clear about that. No that is not possible.

**Comment by domeglic** [comment]
This should be possible by creating multiple rules for each gift.
