### ISSUE TITLE
Free Gift duplicate when Create Order at Backend(Admin Page)

### ISSUE THREAD

**Issue by Osara12** [code4business/freeproduct2#26]
### Preconditions

- Magento version: 2.3.4
- Module version: lastest

### Settings / Sale Rules
 1.Subtotal >= 2500 get free 1 item(1sku)

### Steps to reproduce
1.  Create order at Admin backend
2.  After added some product and Cart subtotal > 2500, the gift will be added to Cart
3.  if I add more products, The gift will duplicate. 
4. after placed order, The gift that duplicated from step 3 will show x2 at Order page.

### Expected result
1.

### Actual result
1.

**Comment by domeglic** [comment]
duplicate of #35
