### ISSUE TITLE
Issue with adding a product to the cart on Magento 2.4.3

### ISSUE THREAD

**Issue by mityaiko** [code4business/freeproduct2#35]
### Preconditions

- Magento version: 2.4.3-p1
- Module version: 1.2.9

Looks like this module is incompatible with 2.4. When the module is activated the second adding of a product to the shopping cart causing the eternal spinner and only page reloading helps. Also when you create an order from the admin panel it adds one gift to each product added and not once to an order.

There was not the problem on older Magento 2.3.5

**Comment by domeglic** [comment]
Hello, sorry for the delay. I wasn't able to reproduce the first bug. I tried adding products a second time and I never got the broken loader.

The admin duplicated gifts problem should be resolved in the version 1.3.0 soon.
