### ISSUE TITLE
How to set subtotal value to "2.5" or show original product price for free gift product item in cart page(currently its showing 0.00) ?

### ISSUE THREAD

**Issue by nkp86** [code4business/freeproduct2#44]
### Preconditions

- Magento version: 2.4.x
- Module version: 

### Settings / Sale Rules

1.  cart price rule to add free product on whole cart amount

### Steps to reproduce
1. add a product to the cart with the particular price value as configured in sales rule
### Expected result
1.

### Actual result
1. 
![image](https://github.com/code4business/freeproduct2/assets/149630413/16d51cb6-b584-4209-8d46-a90056659f08)

**Comment by nkp86** [comment]
Hi @domeglic, could you please provide and solution for the above problem?

**Comment by domeglic** [comment]
Having a product show a price but be excluded in the subtotal doesn't make sense. You would have to adjust magento calculation logic to ignore products but still show their price. It is out of scope for this module.

**Comment by nkp86** [comment]
@domeglic Oh, but I just want to auto-add a free product to the cart only, it should not calculate the subtotal.
Is it possible, for me to adjust the Magento calculation here, 
can you please suggest it so I can achieve it?

<free_original_cart_price_row_total>2.1000</free_original_cart_price_row_total>
