### ISSUE TITLE
Error discount in cart (voucher native)!

### ISSUE THREAD

**Issue by cgsoratto** [code4business/freeproduct2#8]
Hi everyone, I'm in need of a voucher help. I installed the C4B_FreeProduct module. OK!

I have a voucher set up by this module (product gift above $ 99) and I have another voucher set up by the store to give $ 200 off on purchases over $ 200. OK! When the purchase has only 1 voucher enabled, everything works. However, when you have 2 vouchers enabled, a problem occurs. I'll explain: I have a $ 100 product. If I add 4 products of this in the cart, my cart is $ 400 total. Then you activate the toast voucher (over $ 99) and I add the voucher code for purchases over $ 200. Here the problem occurs! The discount voucher, gives the discount only for 1 product of the cart. So if the product has a value of $ 100, the magento places a discount of $ 100 (even if the voucher is set to give $ 200 off).

**Comment by domeglic** [comment]
Is the voucher rule set to use "Fixed amount discount" or "Fixed amount discount for whole cart" ?

**Comment by cgsoratto** [comment]
Fixed amount discount for whole cart (cart_fixed).

It only works if the discount voucher is priority 1 and the gift voucher is priority 0.
If the gift voucher is a priority above the discount voucher, the problem occurs.

**Comment by domeglic** [comment]
I see the problem now, we will have a look into it.

**Comment by domeglic** [comment]
This bug should be fixed now in version 1.2.0.
